#!/bin/bash

set +e

sudo apt-get update
sudo apt-get upgrade -y

snap refresh

flatpak update

if [ -z "$(brew --version 2>&1 >/dev/null)" ]; then brew update && brew upgrade; fi
if [ -z "$(npm --version 2>&1 >/dev/null)" ]; then npm install -g npm@latest; fi
if [ -z "$(yarn --version 2>&1 >/dev/null)" ]; then npm install -g yarn@latest; fi
if [ -z "$(pnpm --version 2>&1 >/dev/null)" ]; then npm install -g pnpm@latest; fi

python -m pip install --upgrade pip
python3 -m pip install --upgrade pip

if [ -z "$(cargo --version 2>&1 >/dev/null)" ]; then cargo install cargo --force; fi
if [ -z "$(rkhunter --version 2>&1 >/dev/null)" ]; then sudo rkhunter --update; fi
if [ -z "$(clamd --version 2>&1 >/dev/null)" ]; then sudo freshclam; fi
if [ -z "$(pihole --version 2>&1 >/dev/null)" ]; then pihole -up; fi

