name: 'Test cli'

on:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3
          - name: Run
            run: chmod +x ./update-all && ./update-all
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}